/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notas_g1;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class ControlNotasSwing extends javax.swing.JFrame {

    /**
     * Creates new form ControlNotasSwing
     */
    public ControlNotasSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTema = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbCarrera = new javax.swing.JLabel();
        lbCiclo = new javax.swing.JLabel();
        lbCum = new javax.swing.JLabel();
        lbMensaje1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfCum = new javax.swing.JTextField();
        cbCarrera = new javax.swing.JComboBox<>();
        cbCiclo = new javax.swing.JComboBox<>();
        lbMateria = new javax.swing.JLabel();
        lbUv = new javax.swing.JLabel();
        lbNota = new javax.swing.JLabel();
        cbMateria1 = new javax.swing.JComboBox<>();
        cbUv1 = new javax.swing.JComboBox<>();
        tfNota1 = new javax.swing.JTextField();
        lbEstado1 = new javax.swing.JLabel();
        cbMateria2 = new javax.swing.JComboBox<>();
        cbUv2 = new javax.swing.JComboBox<>();
        tfNota2 = new javax.swing.JTextField();
        lbEstado2 = new javax.swing.JLabel();
        lbEstado3 = new javax.swing.JLabel();
        tfNota3 = new javax.swing.JTextField();
        cbUv3 = new javax.swing.JComboBox<>();
        cbMateria3 = new javax.swing.JComboBox<>();
        lbEstado4 = new javax.swing.JLabel();
        tfNota4 = new javax.swing.JTextField();
        cbUv4 = new javax.swing.JComboBox<>();
        cbMateria4 = new javax.swing.JComboBox<>();
        lbEstado5 = new javax.swing.JLabel();
        tfNota5 = new javax.swing.JTextField();
        cbUv5 = new javax.swing.JComboBox<>();
        cbMateria5 = new javax.swing.JComboBox<>();
        btCalcular = new javax.swing.JButton();
        lbMensaje = new javax.swing.JTextField();
        btLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lbTema.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        lbTema.setText("CONTROL DE NOTAS");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNombre.setText("NOMBRE");

        lbCarrera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCarrera.setText("CARRERA");

        lbCiclo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCiclo.setText("CICLO");

        lbCum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCum.setText("CUM");

        lbMensaje1.setBackground(new java.awt.Color(204, 255, 204));
        lbMensaje1.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        lbMensaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMensaje1.setOpaque(true);

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfCum.setEditable(false);

        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccion --", "Ingenieria Industrial", "Ingenieria en Sistemas", "Ingenieria Electrica", "Ingenieria en Agronegocios" }));

        cbCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccion --", "Ciclo 01", "Ciclo 02" }));

        lbMateria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMateria.setText("MATERIA");

        lbUv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUv.setText("UV");

        lbNota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNota.setText("NOTA");

        cbMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbUv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tfNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota1ActionPerformed(evt);
            }
        });

        lbEstado1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado1.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado1.setText("Estado");

        cbMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbUv2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbEstado2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado2.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado2.setText("Estado");

        lbEstado3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado3.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado3.setText("Estado");

        cbUv3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        lbEstado4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado4.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado4.setText("Estado");

        tfNota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota4ActionPerformed(evt);
            }
        });

        cbUv4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        lbEstado5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado5.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado5.setText("Estado");

        cbUv5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        btCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCalcular.setText("CALCULAR");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        lbMensaje.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbMensajeActionPerformed(evt);
            }
        });

        btLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cbMateria5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(lbMateria))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(lbUv)
                                .addGap(132, 132, 132)
                                .addComponent(lbNota))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(tfCum, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbUv1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbUv2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbUv3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbUv4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbUv5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbEstado5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbEstado4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btCalcular)
                        .addGap(85, 85, 85)
                        .addComponent(btLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(lbTema))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lbNombre)
                        .addGap(214, 214, 214)
                        .addComponent(lbCarrera)
                        .addGap(175, 175, 175)
                        .addComponent(lbCiclo)
                        .addGap(133, 133, 133)
                        .addComponent(lbCum)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbTema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbCarrera)
                    .addComponent(lbCiclo)
                    .addComponent(lbCum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMateria)
                            .addComponent(lbUv)
                            .addComponent(lbNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbUv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbUv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbUv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btCalcular)
                        .addComponent(btLimpiar))
                    .addComponent(lbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbMensajeActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:

        String carrera = (String) cbCarrera.getSelectedItem();
        String ciclo = (String) cbCiclo.getSelectedItem();
        String nombre = tfNombre.getText();

        if (isInputValid(carrera, ciclo, nombre)) {
            float[] notas = {
                Float.parseFloat(tfNota1.getText()),
                Float.parseFloat(tfNota2.getText()),
                Float.parseFloat(tfNota3.getText()),
                Float.parseFloat(tfNota4.getText()),
                Float.parseFloat(tfNota5.getText())
            };

            int[] uvs = {
                Integer.parseInt((String) cbUv1.getSelectedItem()),
                Integer.parseInt((String) cbUv2.getSelectedItem()),
                Integer.parseInt((String) cbUv3.getSelectedItem()),
                Integer.parseInt((String) cbUv4.getSelectedItem()),
                Integer.parseInt((String) cbUv5.getSelectedItem())
            };

            int reprobado = 0;
            int aprobado = 0;
            float cum = calculateCUM(notas, uvs);

            for (int i = 0; i < notas.length; i++) {
                JLabel lbEstado = getLabelByIndex(i + 1);

                if (notas[i] < 6) {
                    setLabelStatus(lbEstado, "Reprobado", Color.red);
                    reprobado++;
                } else {
                    setLabelStatus(lbEstado, "Aprobado", Color.green);
                    aprobado++;
                }
            }

            String TotalCum = Float.toString(cum);
            String MateriasAprobadas = Integer.toString(aprobado);
            String MateriasReprobadas = Integer.toString(reprobado);

            tfCum.setText(TotalCum);

            lbMensaje.setText(
                nombre + " su estado actual es de " + MateriasAprobadas + " materias aprobadas y " + MateriasReprobadas +
                " reprobadas y su CUM actual es de " + tfCum.getText()
            );
        }
    }//GEN-LAST:event_btCalcularActionPerformed

    private void tfNota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota4ActionPerformed

    private void tfNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota1ActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        cbCarrera.setSelectedIndex(0);
    cbCiclo.setSelectedIndex(0);
    cbMateria1.setSelectedIndex(0);
    cbMateria2.setSelectedIndex(0);
    cbMateria3.setSelectedIndex(0);
    cbMateria4.setSelectedIndex(0);
    cbMateria5.setSelectedIndex(0);
    tfNota1.setText("");
    tfNota2.setText("");
    tfNota3.setText("");
    tfNota4.setText("");
    tfNota5.setText("");
    tfNombre.setText("");
    cbUv1.setSelectedIndex(0);
    cbUv2.setSelectedIndex(0);
    cbUv3.setSelectedIndex(0);
    cbUv4.setSelectedIndex(0);
    cbUv5.setSelectedIndex(0);

    // Clear labels and text fields for results
    lbEstado1.setText("");
    lbEstado2.setText("");
    lbEstado3.setText("");
    lbEstado4.setText("");
    lbEstado5.setText("");
    tfCum.setText("");
    lbMensaje.setText("");
    }//GEN-LAST:event_btLimpiarActionPerformed

    
  // Validaciones para que solo se puedan ingresar numeros o letras en el campo correspondiente
 
    private void tfNota1KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
        // Cada vez que el usuario presione una tecla se genera un evento y se almacena en evt
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNota2KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNota3KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNota4KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNota5KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {                                  
       
        // KeyTyped = evento de tecla
         char c = evt.getKeyChar(); // obteniendo el carácter ingresado desde el evento de tecla (evt). getKeyChar()
                                    // Devuelve el caracter de la tecla que se presionó
        if((c<'a' || c>'z') && (c<'A' || c>'Z') //Verifica si el carácter está fuera del rango de letras minúsculas y mayúsculas.
                && !(Character.isSpaceChar(c))) //Verifica si el carácter no es un espacio.
            evt.consume(); // Si el carácter ingresado no es una letra ni un espacio, este comando consume el evento de tecla
                           // así que no se mostrará en el campo de texto
    }          
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlNotasSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlNotasSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlNotasSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlNotasSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlNotasSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JComboBox<String> cbCiclo;
    private javax.swing.JComboBox<String> cbMateria1;
    private javax.swing.JComboBox<String> cbMateria2;
    private javax.swing.JComboBox<String> cbMateria3;
    private javax.swing.JComboBox<String> cbMateria4;
    private javax.swing.JComboBox<String> cbMateria5;
    private javax.swing.JComboBox<String> cbUv1;
    private javax.swing.JComboBox<String> cbUv2;
    private javax.swing.JComboBox<String> cbUv3;
    private javax.swing.JComboBox<String> cbUv4;
    private javax.swing.JComboBox<String> cbUv5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCiclo;
    private javax.swing.JLabel lbCum;
    private javax.swing.JLabel lbEstado1;
    private javax.swing.JLabel lbEstado2;
    private javax.swing.JLabel lbEstado3;
    private javax.swing.JLabel lbEstado4;
    private javax.swing.JLabel lbEstado5;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JTextField lbMensaje;
    private javax.swing.JLabel lbMensaje1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNota;
    private javax.swing.JLabel lbTema;
    private javax.swing.JLabel lbUv;
    private javax.swing.JTextField tfCum;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNota1;
    private javax.swing.JTextField tfNota2;
    private javax.swing.JTextField tfNota3;
    private javax.swing.JTextField tfNota4;
    private javax.swing.JTextField tfNota5;
    // End of variables declaration//GEN-END:variables

  private boolean isInputValid(String carrera, String ciclo, String nombre) {
    boolean isValid = true;

    if ("Elegir una opción".equals(carrera) || "Elegir una opción".equals(ciclo) || nombre.isEmpty()) {
        isValid = false;
        JOptionPane.showMessageDialog(this, "Llene todos los campos solicitados.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    return isValid;
}

    private float calculateCUM(float[] notas, int[] uvs) {
    float totalNotas = 0;
    int totalUVs = 0;

    for (int i = 0; i < notas.length; i++) {
        totalNotas += notas[i] * uvs[i];
        totalUVs += uvs[i];
    }

    return totalNotas / totalUVs;
}

private JLabel getLabelByIndex(int index) {
        return switch (index) {
            case 1 -> lbEstado1;
            case 2 -> lbEstado2;
            case 3 -> lbEstado3;
            case 4 -> lbEstado4;
            case 5 -> lbEstado5;
            default -> null;
        };
}

private void setLabelStatus(JLabel label, String text, Color color) {
    label.setOpaque(true);
    label.setText(text);
    label.setBackground(color);
}

}
